# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('StellaPay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdevice',
            name='uuid',
            field=models.CharField(max_length=16),
        ),
    ]
