# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-22 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('StellaPay', '0002_auto_20200322_2311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
