# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-22 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('StellaPay', '0004_auto_20200322_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
